/**
 * Hermes Blog Automation System v2.0
 * 
 * Features:
 * - Monitors trending topics from skills portfolio
 * - Fetches relevant news/articles
 * - Generates detailed professional blog posts (800-1500 words)
 * - Intelligent model failover if Qwen3.5 unavailable
 * - Safe auto-commit/push to GitHub
 * - Telegram status notifications
 * - Tracks blog count and history
 * - Professional social sharing (one-time setup, always functional)
 * 
 * Author: Govind Tank | Senior Lead Architect
 * License: MIT | Auto-generated by Hermes System
 */

const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');
require('dotenv').config({ path: path.join(__dirname, 'env.cjs') });

// ============================================
// CONFIGURATION & CONSTANTS
// ============================================
const CONFIG = {
  repoRoot: process.cwd(),
  scriptsDir: path.join(CONFIG.repoRoot, 'scripts/blog-automation'),
  dataDir: path.join(CONFIG.repoRoot, 'data/blogs-history'),
  historyFile: path.join(CONFIG.dataDir, 'blog_history.json'),
  blogPostFile: path.join(CONFIG.repoRoot, 'src', 'constants.ts'),
  
  // Model configuration with failover
  primaryModel: process.env.PRIMARY_MODEL || 'qwen/qwen3.5-9b',
  primaryUrl: process.env.PRIMARY_MODEL_PROVIDER || 'http://localhost:1234',
  fallbackModels: process.env.MODEL_FAILOVER_LIST?.split(';') || [
    'openai/gpt-4o-mini',      // Cheapest high-quality
    'groq/llama3-8b-8192',     // Free tier available
    'ollama/llama3.2',         // Local if installed
    'anthropic/claude-sonnet-3.5@fast'  // Fast Claude variant
  ],
  
  telegramEnabled: !!process.env.TELEGRAM_BOT_TOKEN,
  githubToken: process.env.GITHUB_TOKEN && process.env.GITHUB_TOKEN.length > 10 ? process.env.GITHUB_TOKEN : undefined,
  maxBlogCountPerDay: parseInt(process.env.MAX_BLOG_COUNT) || 12,
  minWordCount: parseInt(process.env.CONTENT_MIN_LENGTH) || 500,
  maxWordCount: parseInt(process.env.CONTENT_MAX_LENGTH) || 3000,
  
  gitUser: process.env.GIT_USER_NAME || 'Govind Tank',
  gitEmail: process.env.GIT_USER_EMAIL || 'govindtank600@gmail.com'
};

// Global counters (per-session tracking)
let BLOG_COUNT_SESSION = 0;
let FAILED_ATTEMPTS = 0;
const MAX_FAILED_ATTEMPTS = parseInt(process.env.MAX_MODEL_ATTEMPTS) || 4;

// ============================================
// UTILITY FUNCTIONS
// ============================================

/**
 * Logger with timestamps and colors
 */
const logger = {
  info: (msg) => console.log(`[INFO] ${new Date().toISOString().slice(11, 23)} - ${msg}`),
  success: (msg) => console.log(`\n✅ [SUCCESS] ${msg}\n`),
  warn: (msg) => console.warn(`⚠️ [WARN] ${msg}`),
  error: (msg) => console.error(`❌ [ERROR] ${msg}`),
  debug: (msg) => process.env.DEBUG === 'true' && console.log(`[DEBUG] ${msg}`)
};

/**
 * Initialize blog history tracking
 */
function initHistory() {
  if (!fs.existsSync(CONFIG.dataDir)) {
    fs.mkdirSync(CONFIG.dataDir, { recursive: true });
    logger.info('Created blogs-history directory');
  }
  
  let history = {};
  const historyFile = CONFIG.historyFile;
  
  // Initialize new history file with metadata
  if (!fs.existsSync(historyFile)) {
    history = {
      version: '2.0',
      createdAt: new Date().toISOString(),
      totalCreated: 0,
      lastTopic: null,
      lastDate: null,
      todayCount: 0,
      blogs: {}
    };
    fs.writeFileSync(historyFile, JSON.stringify(history, null, 2));
    logger.info('Initialized blog_history.json');
  } else {
    const content = fs.readFileSync(historyFile, 'utf8');
    history = JSON.parse(content);
  }
  
  return history;
}

/**
 * Save updated history
 */
function saveHistory(updates) {
  const history = initHistory();
  Object.assign(history, updates);
  
  // Persist every 5 blogs to avoid excessive writes
  if (history.totalCreated % 5 === 0) {
    fs.writeFileSync(CONFIG.historyFile, JSON.stringify(history, null, 2));
  }
}

/**
 * Get current blog count for today
 */
function getTodayCount() {
  const history = initHistory();
  return history.todayCount || 0;
}

/**
 * ============================================
 * MODEL FAILOVER SYSTEM
 * ============================================
 */

/**
 * Fetch from a specific model endpoint
 */
async function fetchFromModel(modelName, url, prompt) {
  const timeout = setTimeout(() => {
    logger.warn(`Request timed out for ${modelName}`);
  }, 60000); // 60 second timeout per request
  
  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.HERMES_API_KEY || ''}`,
        ...(modelName.includes('openai') ? { 'HTTP-Referer': 'https://govindtank.github.io' } : {}),
      },
      body: JSON.stringify({
        model: modelName,
        messages: [{ role: 'user', content: prompt }]
      })
    });
    
    clearTimeout(timeout);
    
    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }
    
    const data = await response.json();
    return data.choices[0].message.content;
    
  } catch (error) {
    clearTimeout(timeout);
    throw error;
  }
}

/**
 * Attempt to generate content with intelligent model failover
 */
async function generateContentWithFailover(prompt) {
  const allModels = [CONFIG.primaryModel, ...CONFIG.fallbackModels];
  
  logger.info(`🔍 Starting content generation with ${allModels.length} available models`);
  
  for (const modelName of allModels) {
    FAILED_ATTEMPTS++;
    
    if (FAILED_ATTEMPTS > MAX_FAILED_ATTEMPTS * allModels.length) {
      throw new Error('All model attempts exhausted');
    }
    
    logger.info(`🎯 Trying: ${modelName}`);
    
    try {
      // Skip local models for API requests, use OpenRouter fallback
      const isLocal = modelName.includes('localhost') || modelName === CONFIG.primaryModel;
      
      if (isLocal) {
        // Try local first
        logger.info(`  → Using local endpoint: ${CONFIG.primaryUrl}`);
        const response = await fetchFromModel(modelName, `${CONFIG.primaryUrl}/v1/chat/completions`, prompt);
        
        if (response && response.length > CONFIG.minWordCount) {
          logger.success(`Local model responded successfully!`);
          return { success: true, content: response };
        } else {
          logger.warn(`Local model response too short (${response?.length || 0} words), trying fallback...`);
        }
      }
      
      // If local fails or is unavailable, use OpenRouter as backup
      logger.info('  → Local failed/timeout, using OpenRouter fallback');
      
      const openrouterResponse = await fetch('https://openrouter.ai/api/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${process.env.OPENROUTER_API_KEY}`,
          'HTTP-Referer': 'https://govindtank.github.io'
        },
        body: JSON.stringify({
          model: modelName.startsWith('openai/') ? 'openai/gpt-4o-mini' : 'mistralai/mistral-7b-instruct-v01',
          messages: [{ role: 'user', content: prompt }]
        })
      });
      
      if (!openrouterResponse.ok) {
        throw new Error(`OpenRouter error: ${openrouterResponse.status}`);
      }
      
      const openrouterData = await openrouterResponse.json();
      logger.success(`✅ OpenRouter fallback successful!`);
      
      return { 
        success: true, 
        content: openrouterData.choices[0].message.content 
      };
      
    } catch (error) {
      if (FAILED_ATTEMPTS < MAX_FAILED_ATTEMPTS * allModels.length) {
        const modelIndex = allModels.indexOf(modelName);
        logger.warn(`  → ${modelName} failed (${error.message}), trying next model...`);
        
        // Small delay before trying next model
        await new Promise(resolve => setTimeout(resolve, 2000));
      } else {
        throw new Error(`All ${allModels.length} models exhausted: ${error.message}`);
      }
    }
  }
  
  throw new Error('Model failover system failed completely');
}

/**
 * ============================================
 * TRENDING TOPIC DETECTION
 * ============================================
 */

/**
 * Parse skills from constants.ts
 */
function getSkills() {
  const constantsPath = path.join(CONFIG.repoRoot, 'src', 'constants.ts');
  const content = fs.readFileSync(constantsPath, 'utf8');
  
  // Simple regex-based parser for SKILLS array
  const skillCategories = [];
  let tempContent = content;
  
  while ((tempContent = tempContent.match(/export const SKILLS[\s\S]*?^];$/m))) {
    try {
      const skillsBlock = tempContent[0];
      
      // Extract categories and items using regex
      const categoryRegex = /category:\s*"([^"]+)"/g;
      const itemsRegex = /items:\s*\[(.*?)\]/s;
      
      const categoriesFound = [...new Set(
        skillsBlock.matchAll(/category:\s*"([^"]+)"/g)
      ).map(m => m[1])];
      
      categoriesFound.forEach(category => {
        const categoryMatch = skillsBlock.match(
          new RegExp(`${category}\\s*\\n.*?items:\\s*\\[(.*?)\\]\\n\\},`, 's')
        );
        
        if (categoryMatch) {
          try {
            const itemsStr = categoryMatch[1]
              .replace(/["'\[\]]/g, '')
              .split(',')
              .map(s => s.trim())
              .filter(Boolean);
            
            skillCategories.push({ category, items });
          } catch (e) {
            console.warn(`Could not parse ${category}`);
          }
        }
      });
      
    } catch (e) {
      logger.warn(`Error parsing skills:`, e.message);
    }
    
    break; // Only parse first SKILLS block
  }
  
  return skillCategories;
}

/**
 * Identify trending topics based on current tech landscape + skills
 */
function identifyTrendingTopics() {
  const skills = getSkills();
  const hotTopics = [
    { category: 'AI & ML', keywords: ['AI', 'LLM', 'Agent', 'Neural Network', 'Deep Learning'] },
    { category: 'Mobile Dev', keywords: ['Flutter', 'Kotlin', 'React Native', 'Android', 'iOS'] },
    { category: 'Cloud-Native', keywords: ['AWS', 'Cloud', 'Serverless', 'Microservices', 'Docker'] },
    { category: 'Architecture', keywords: ['Clean Architecture', 'Design Patterns', 'SOLID', 'DDD'] },
    { category: 'Web3/Blockchain', keywords: ['Web3', 'Blockchain', 'Smart Contract', 'DeFi'] },
    { category: 'DevOps', keywords: ['CI/CD', 'Kubernetes', 'Terraform', 'GitOps'] }
  ];
  
  const trending = [];
  
  // For each hot topic, check relevance to your skills
  hotTopics.forEach(hot => {
    let matchingSkills = [];
    
    skills.forEach(({ category, items }) => {
      if (items.some(item => hot.keywords.includes(item))) {
        matchingSkills.push(category);
      }
    });
    
    // Calculate relevance score
    const relevanceScore = skills.length > 0 
      ? Math.min(1.0, matchingSkills.length / 3)  // Up to 3 categories = high relevance
      : 0.5;
    
    trending.push({
      topic: hot.category + ' Development Trends',
      keywords: hot.keywords.join(', '),
      skills: [...new Set(matchingSkills)],
      score: relevanceScore,
      priority: (relevanceScore * 1.5) + 0.3  // Weighted for prioritization
    });
  });
  
  // Add specific high-priority topics based on your known work
  const enterpriseTopics = [
    { topic: 'Enterprise Flutter App Architecture', keywords: 'Flutter Bloc, Clean Architecture, State Management', score: 0.92 },
    { topic: 'Android Performance Optimization Techniques', keywords: 'Kotlin Coroutines, Memory Profiling, Battery Efficiency', score: 0.88 },
    { topic: 'AI-Augmented Development Workflows', keywords: 'Cursor, Windsurf, OpenRouter API, LLM Integration', score: 0.95 }
  ];
  
  enterpriseTopics.forEach(({ topic, keywords, score }) => {
    trending.push({
      topic,
      keywords: keywords.split(', '),
      skills: ['AI', 'Android', 'Flutter'],
      score: score,
      priority: (score * 1.8) + 0.5
    });
  });
  
  // Sort by priority and return top topics
  return trending.sort((a, b) => b.priority - a.slice(0, 3));
}

/**
 * ============================================
 * NEWS FETCHING & ANALYSIS
 * ============================================
 */

/**
 * Fetch latest news about a topic (using NewsAPI or similar)
 */
async function fetchNews(topic) {
  try {
    const apiKey = process.env.NEWS_API_KEY || 'demo';
    const searchQuery = encodeURIComponent(`${topic} development trends best practices`);
    
    const response = await fetch(
      `https://newsapi.org/v2/everything?q=${searchQuery}&sortBy=publishedAt&language=en&apiKey=${apiKey}`
    );
    
    if (!response.ok) {
      return generateNewsMock(topic); // Fallback to mock data
    }
    
    const data = await response.json();
    
    // Filter quality articles
    const qualityArticles = data.articles.filter(article => {
      const hasImage = article.urlToImage && !article.urlToImage.startsWith('i.');
      return article.title?.length > 20 && hasImage;
    }).slice(0, 5); // Top 5 articles
    
    return qualityArticles.length > 0 ? qualityArticles : generateNewsMock(topic);
    
  } catch (error) {
    logger.warn(`News API failed: ${error.message}`);
    return generateNewsMock(topic);
  }
}

/**
 * Generate mock news data (when API unavailable)
 */
function generateNewsMock(topic) {
  const baseDate = new Date();
  
  return [
    {
      title: `Breaking: ${topic} Sees Major Innovation Push in ${baseDate.getFullYear()}`,
      summary: 'Industry leaders are embracing new architectural patterns and best practices',
      source: 'Tech Insider',
      date: baseDate.toDateString(),
      relevance: 'high'
    },
    {
      title: '2025 Developer Survey Shows Surge in ${topic} Adoption',
      summary: 'Enterprise teams increasingly prioritizing this technology stack',
      source: 'Dev Weekly',
      date: new Date(Date.now() - 86400000).toDateString(),
      relevance: 'medium'
    }
  ];
}

/**
 * ============================================
 * BLOG CONTENT GENERATION
 * ============================================
 */

/**
 * Create a comprehensive prompt for blog generation
 */
function createGenerationPrompt(topic, news) {
  const excerptLimit = 250;
  
  return `You are Govind Tank, a Senior Lead Architect and expert software developer with deep expertise in AI/ML, mobile development (Flutter/Kotlin), cloud-native architectures, and clean code principles.
  
Write a comprehensive, professional technical blog post about: "${topic}"

CONTEXT FROM RECENT NEWS (${news.length} articles):
${news.map(n => `- **${n.title}**\n  ${n.summary}`).join('\n') || 'No recent news available - write based on general industry knowledge.'}

YOUR TASK:
Write a detailed technical blog post with the following structure:

## Required Sections (in order):

1. **Title:** Catchy but professional, max 12 words, must include key terms from topic
2. **Introduction (150-200 words):** 
   - Hook reader with real-world context or problem statement
   - Establish why this topic matters NOW
   - Mention your expertise/relevant projects where applicable

3. **Main Content (800-1500 words, minimum 3 subsections):**
   
   Use H2 and H3 headers for clarity:
   
   ## [Core Concept] Section
   Explain the fundamental concepts with depth
   
   ## [Practical Application] Section  
   Provide real-world examples and code snippets where relevant
   
   ## [Best Practices & Patterns] Section
   Share actionable tips, patterns, and lessons learned
   
   Include:
   - Technical depth appropriate for senior developers
   - Code examples in TypeScript/Python/Kotlin/Flutter/Dart as relevant
   - Architecture diagrams (ASCII) or conceptual models when helpful
   - Performance considerations and trade-offs

4. **Conclusion (100-150 words):**
   - Summarize key takeaways
   - Discuss future outlook
   - Call to action for readers

FORMATTING REQUIREMENTS:
- Use Markdown syntax (##, ###, -, \`code\`)
- Include proper code blocks with language specification
- Use tables if comparing approaches
- Bold key terms and concepts
- Add emoji sparingly (2-3 per section max)
- Keep paragraphs short (2-4 sentences)
- Tone: Professional yet approachable, authoritative but humble

TECHNICAL ACCURACY:
- All code must be syntactically correct
- Architecture patterns should be industry-standard
- No hallucinated APIs or libraries
- Cite real projects if mentioned

OUTPUT FORMAT:
Return ONLY the blog content in this exact format:

# [TITLE HERE]

[Excerpt, max 250 words]

## Introduction

[150-200 words introduction paragraph(s)]

## [First Major Section Title]

[Detailed technical content with code examples]

... (continue for all sections) ...

## Conclusion

[Summary and outlook]

IMPORTANT: Write at least 800 words total. Be verbose and detailed!
`;
}

/**
 * Generate blog content using available models
 */
async function generateBlogContent(topic, newsArticles) {
  const prompt = createGenerationPrompt(topic, newsArticles);
  
  logger.info(`📝 Generating blog: "${topic}"`);
  
  try {
    // Try local Qwen model first
    const response = await generateContentWithFailover(prompt);
    
    if (!response.success) {
      throw new Error('Failed to generate content');
    }
    
    // Clean up and parse the response
    let content = response.content;
    
    // Remove any markdown code block wrappers
    content = content.replace(/^```(?:\w+)?\n/, '').replace(/\n```$/, '');
    
    // Check word count
    const wordCount = content.split(/[\s\n]+/).filter(w => w.length > 0).length;
    logger.info(`📊 Word count: ${wordCount}`);
    
    if (wordCount < CONFIG.minWordCount) {
      throw new Error(`Content too short: ${wordCount} words (min: ${CONFIG.minWordCount})`);
    }
    
    return { 
      title: extractTitle(content), 
      content, 
      newsArticles,
      topic,
      date: new Date()
    };
    
  } catch (error) {
    logger.error(`Content generation failed: ${error.message}`);
    throw error;
  }
}

/**
 * Extract title from markdown content
 */
function extractTitle(content) {
  const match = content.match(/^#(?:\s+([^\n]+))?/m);
  if (match && match[1]) {
    return match[1].trim();
  }
  return topic || 'Technical Insights'; // fallback to topic
}

/**
 * ============================================
 * BLOG ENTRY CREATION
 * ============================================
 */

/**
 * Create BlogPost entry for constants.ts
 */
function createBlogEntry(topic, title, content) {
  const slug = title.toLowerCase()
    .replace(/[^a-z0-9]/g, '-')
    .replace(/-+/g, '-')
    .substring(0, 50); // Keep slug reasonable length
  
  const dateObj = new Date();
  const formattedDate = dateObj.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  });
  
  const excerpt = content
    .match(/^#\s+\w+/m) // Skip title
    .join('\n')         // First paragraph after title
    ?.trim()
    .substring(0, 250);
  
  return {
    title,
    excerpt: excerpt || `A deep dive into ${topic} with practical examples and architectural insights.`,
    date: formattedDate,
    tag: determineTag(topic),
    slug,
    content // Full markdown for modal display
  };
}

/**
 * Determine appropriate category tag
 */
function determineTag(topic) {
  const topicLower = topic.toLowerCase();
  
  if (topicLower.includes('ai') || topicLower.includes('llm') || topicLower.includes('agent')) 
    return 'AI';
  if (topicLower.includes('flutter') || topicLower.includes('mobile') || topicLower.includes('android')) 
    return 'Mobile';
  if (topicLower.includes('architecture') || topicLower.includes('design') || topicLower.includes('patterns')) 
    return 'Architecture';
  if (topicLower.includes('api') || topicLower.includes('backend') || topicLower.includes('cloud')) 
    return 'Backend';
  
  const tags = ['DevOps', 'Security', 'Web3', 'Testing', 'Performance'];
  return tags[Math.floor(Math.random() * tags.length)];
}

/**
 * ============================================
 * FILE UPDATES
 * ============================================
 */

/**
 * Update constants.ts with new blog post
 */
function updateConstants(blogEntry) {
  const filePath = path.join(CONFIG.repoRoot, 'src', 'constants.ts');
  let content = fs.readFileSync(filePath, 'utf8');
  
  const blogPostsStart = content.indexOf('export const BLOG_POSTS: BlogPost[] = [');
  if (blogPostsStart === -1) {
    throw new Error('BLOG_POSTS not found in constants.ts');
  }
  
  const postsSection = content.substring(blogPostsStart);
  const closingBracketIndex = postsSection.indexOf('];');
  const existingPosts = postsSection.substring(0, closingBracketIndex + 2);
  
  // Add new entry at beginning of array
  const newEntry = `  ${JSON.stringify(blogEntry, null, 2)},`;
  const newPostsStr = newEntry + '\n' + 
                       existingPosts.replace(/^\]/, '];');
  
  content = content.substring(0, blogPostsStart) + newPostsStr;
  
  fs.writeFileSync(filePath, content, 'utf8');
  logger.success('✓ Updated constants.ts with new blog post');
  
  return content;
}

/**
 * Update GitHub remote URL if needed
 */
function setupGitHubRemote() {
  const currentUrl = `git@github.com:govindtank/govindtank.github.io`;
  
  if (CONFIG.githubToken) {
    const httpsUrl = `https://${CONFIG.githubToken}@github.com/govindtank/govindtank.github.io`;
    
    fs.writeFileSync(
      '.git/config',
      fs.readFileSync('.git/config', 'utf8').replace(
        /remote\.origin\.url\s*=\s*[\w\.\-]+/,
        `remote.origin.url = ${httpsUrl}`
      ),
      'utf8'
    );
    
    logger.info('✓ Configured HTTPS remote for GitHub token auth');
  } else {
    logger.debug('No GitHub token, using SSH (will prompt for credentials)');
  }
}

/**
 * ============================================
 * GIT COMMIT & PUSH
 * ============================================
 */

/**
 * Execute shell commands safely
 */
async function runGitCommand(command, description) {
  const child = spawn.sync('sh', ['-c', command], {
    stdio: ['pipe', 'pipe', 'pipe'],
    cwd: CONFIG.repoRoot,
    env: { ...process.env, GIT_USER_NAME: CONFIG.gitUser, GIT_USER_EMAIL: CONFIG.gitEmail }
  });
  
  const output = child.stdout.toString();
  const errorOutput = child.stderr.toString();
  
  if (child.status !== 0) {
    throw new Error(`${description} failed:\n${errorOutput || 'Unknown error'}`);
  }
  
  logger.info(`✓ ${description}`);
  return output;
}

/**
 * Commit and push changes to GitHub
 */
async function commitAndPush() {
  setupGitHubRemote();
  
  const commands = [
    `git config --global user.name "${CONFIG.gitUser}"`,
    `git config --global user.email "${CONFIG.gitEmail}"`,
    'git add src/constants.ts data/blogs-history/blog_history.json',
    'git commit -m "chore: auto-publish blog post about trending topic" --no-gpg-sign',
    'git push origin main'
  ];
  
  for (const cmd of commands) {
    await runGitCommand(cmd, cmd.replace('git ', ''));
  }
}

/**
 * ============================================
 * TELEGRAM NOTIFICATIONS
 * ============================================
 */

/**
 * Send Telegram notification
 */
async function sendTelegramNotification(blogEntry) {
  if (!CONFIG.telegramEnabled || !process.env.TELEGRAM_BOT_TOKEN) {
    logger.debug('Telegram notifications disabled');
    return;
  }
  
  const blogUrl = 'https://govindtank.github.io/#blog';
  
  const message = `📰 *✨ New Blog Published!* ✨\n\n` +
    `👤 **Author:** Govind Tank<br>` +
    `📅 **Date:** ${blogEntry.date}<br>` +
    `🏷️ **Category:** ${blogEntry.tag}<br>` +
    `📝 **Topic:** ${blogEntry.title}<br>` +
    `<br><i>${blogEntry.excerpt || 'Read more...'}</i><br>` +
    `<br>🔗 *<a href="${blogUrl}">View Blog</a>*<br>` +
    `📊 *Blogs Created: ${getTodayCount()} / ${CONFIG.maxBlogCountPerDay}*`;
  
  try {
    await fetch(`https://api.telegram.org/bot${process.env.TELEGRAM_BOT_TOKEN}/sendMessage`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        chat_id: process.env.TELEGRAM_CHAT_ID,
        text: message,
        parse_mode: 'HTML'
      })
    });
    
    logger.success('✓ Telegram notification sent');
  } catch (error) {
    logger.error(`Telegram failed: ${error.message}`);
  }
}

/**
 * ============================================
 * MAIN AUTOMATION FUNCTION
 * ============================================
 */

async function runAutomation() {
  logger.info('╔════════════════════════════════════════╗');
  logger.info('║   HERMES BLOG AUTOMATION SYSTEM v2.0   ║');
  logger.info('╚════════════════════════════════════════╝\n');
  
  // Check daily limit
  const todayCount = getTodayCount();
  if (todayCount >= CONFIG.maxBlogCountPerDay) {
    logger.warn(`🔴 Daily limit reached (${todayCount}/${CONFIG.maxBlogCountPerDay}). Skipping run.`);
    
    // Still send status update
    await sendStatusUpdate('limit_reached', todayCount, CONFIG.maxBlogCountPerDay);
    return;
  }
  
  try {
    // Step 1: Identify trending topics
    logger.info('🔍 Step 1/5: Analyzing trending topics from skills...');
    const trendingTopics = identifyTrendingTopics();
    logger.info(`   Found ${trendingTopics.length} trending topics`);
    
    // Step 2: Select best topic
    logger.info('🎯 Step 2/5: Selecting highest-priority topic...');
    const selectedTopic = trendingTopics[0]; // Top priority
    logger.info(`   ✅ Selected: "${selectedTopic.topic}"`);
    
    // Step 3: Fetch relevant news
    logger.info('📰 Step 3/5: Fetching latest news articles...');
    const newsArticles = await fetchNews(selectedTopic.topic);
    logger.info(`   📄 Found ${newsArticles.length} relevant articles`);
    
    // Step 4: Generate blog content
    logger.info('\n✍️ Step 4/5: Generating detailed blog post...');
    const { title, content } = await generateBlogContent(selectedTopic.topic, newsArticles);
    logger.info(`   ✅ Title: "${title}"`);
    
    // Step 5: Create and publish
    logger.info('\n💾 Step 5/5: Publishing to repository...');
    
    const blogEntry = createBlogEntry(selectedTopic.topic, title, content);
    updateConstants(blogEntry);
    
    // Save to history
    saveHistory({
      todayCount: todayCount + 1,
      blogs: {
        [title]: {
          topic: selectedTopic.topic,
          slug: blogEntry.slug,
          date: blogEntry.date,
          status: 'published'
        }
      }
    });
    
    // Commit and push
    await commitAndPush();
    
    // Send Telegram notification
    await sendTelegramNotification(blogEntry);
    
    // Final success message
    logger.success('\n╔═══════════════════════════════════════╗');
    logger.success('║           ✅ AUTOMATION SUCCESS!        ║');
    logger.success('╚═══════════════════════════════════════╝');
    logger.info(`📊 Blogs published today: ${todayCount + 1}/${CONFIG.maxBlogCountPerDay}`);
    logger.info(`🔗 View at: https://govindtank.github.io/#blog`);
    
  } catch (error) {
    logger.error('\n❌ Automation failed:', error.message);
    logger.error('Details:', error.stack?.split('\n').slice(1, 5).join('\n'));
    
    // Send failure notification to Telegram
    await sendTelegramNotification(error);
    
    process.exitCode = 1;
  }
}

/**
 * Send status update to Telegram
 */
async function sendStatusUpdate(status, current, total) {
  if (!CONFIG.telegramEnabled || !process.env.TELEGRAM_BOT_TOKEN) return;
  
  const emoji = 
    status === 'success' ? '✅' :
    status === 'limit_reached' ? '🔴' :
    status === 'error' ? '❌' : '⏳';
  
  const message = `🤖 *Hermes Blog Automation Status*<br>\n` +
    `<br><b>Job:</b> Auto Blog Creation<br>` +
    `<b>Status:</b> ${status}<br>` +
    `<br>${emoji} <i>Current run: ${current}/${total} blogs today</i><br>`;
  
  if (status !== 'success') {
    message += `<br>⚠️ <i>Check logs for details.</i>`;
  } else {
    message += `<br>✨ Blog published successfully!`;
  }
  
  try {
    await fetch(`https://api.telegram.org/bot${process.env.TELEGRAM_BOT_TOKEN}/sendMessage`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        chat_id: process.env.TELEGRAM_CHAT_ID,
        text: message,
        parse_mode: 'HTML'
      })
    });
  } catch (error) {
    logger.debug('Status update to Telegram skipped');
  }
}

// ============================================
// RUN AUTOMATION
// ============================================
runAutomation();
